version: '3'

services:
  api:
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - 3333:3000
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
  adminer:
    image: adminer
    ports:
      - 8888